url: "https://tamacodechi.github.io"
baseurl: "tamacodechi.github.io"
title: "Pilar's Place"

plugins: []

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
